version: '3'
services:
  app:
    container_name: dockerized-vue-app
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - '.:/app'
        - '/app/node_modules'
    ports:
        - '80:80'
    environment:
        - NODE_ENV=production 
