# docker-compose.yml
version: "2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app-dietacerta
    ports:
      - "8001:8001"
    command: yarn start
